on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
      - uses: actions/checkout@v4
      - run: ls
      - run: tsc --version
      - run: tsc --init && tsc
      - run: ls

      # - run: docker --version
      # - run: docker image ls
      # - run: docker pull nginx
      # - run: docker image ls

