on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
      - run: node --version
      - run: npm --version
      - run: tsc --version
      - run: npm i -g typescript
      - run: docker --version
      - run: docker image ls
      - run: docker pull nginx
      - run: docker image ls

  job2:
    runs-on: windows-latest
    steps:
      - run: pwd
      - run: ls
      - run: node --version
      - run: npm --version
      - run: npm i -g typescript
      - run: tsc --version
      - run: docker --version